version: '3.7'

networks:
  simple_feed:
    driver: ${NETWORKS_DRIVER}

services:
  mongodb:
    image: simple_feed/mongodb
    container_name: simple_feed_mongodb
    build:
      context: .
      dockerfile: mongodb/Dockerfile
      args:
        MONGO_VERSION: ${MONGO_VERSION}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - './mongodb/data:/data/db'
    ports:
      - '${MONGO_EXPOSE_PORT}:${MONGO_INTERNAL_PORT}'
    networks:
      - simple_feed
